### ISSUE TITLE
Add code lint to the CI

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web-app-dicom-viewer#19]
Would be great to have a code lint pipeline in the CI.

![Screenshot from 2024-02-19 16-34-47](https://github.com/owncloud/web-app-dicom-viewer/assets/52366632/02ff1eb0-0cd8-44a7-afa7-35c41c9094b9)

Motivations:
- beautify code
- early code smells detection

**Comment by koebel** [comment]
good point! 
@nabim777 can you add this?

**Comment by nabim777** [comment]
Okay @koebel
