### ISSUE TITLE
display all metadata tags that are available in .dcm format

### ISSUE THREAD

**Issue by koebel** [owncloud/web-app-dicom-viewer#6]
The [dicom data standard](https://dicom.nema.org/dicom/2013/output/chtml/part01/PS3.1.html) forsees tags for more metadata than the current dicom-viewer implementation offers. The following website offers an overview of all available [dicom tags](https://www.dicomlibrary.com/dicom/dicom-tags/) (tags and corresponding codes). However in many .dcm files, these additional tags don't contain any values. If it is of value for our use cases, the additional tags and corresponding values could also be displayed in the metadata sidebar of the dicom-viewer.

**Comment by koebel** [comment]
According to meeting with Tobias today twe should add all dicom tags that are available and not yet displayed in the viewer at the bottom of the list in the sidebar under "other information".

**Comment by Salipa-Gurung** [comment]
If my understanding is correct, then all metadata tags must be shown. Does this imply that we must show the additional tags even in cases when the corresponding values are absent from the DICOM file or may we show only those additional tags with a corresponding value in the DICOM file?

cc: @tbsbdr @koebel

**Comment by koebel** [comment]
@Salipa-Gurung would you mind to add the screenshots of the two suggested solutions that you showed me to this conversation?
- Option 1: show all Dicom tags in the side bar, even if many of them contain no value. It's a very long list of tags and in many instances, many of these tags won't contain any data...
- Option 2: show only Dicom tags in the UI that contain a value for the given Dicom image and hide all the other tags. The problem with this option is that maybe in some sections (like "Study Information", "Series Information", ...) there wouldn't be any tag, which would be confusing to the user. This could be handled by even hiding the corresponding section title or showing some message like "no information available" under the section title.

**Comment by Salipa-Gurung** [comment]
| Option 1| Option 2 |
--|--
| ![Screenshot from 2024-09-09 14-55-23](https://github.com/user-attachments/assets/3b2af8f9-f932-4dca-81e8-132bc79fd613) | ![Screenshot from 2024-09-09 14-56-28](https://github.com/user-attachments/assets/3a3f2121-669c-467b-bb58-71fec79ec5ea) |

**Comment by koebel** [comment]
@tbsbdr which option do you think is better for our use case?
