### ISSUE TITLE
Update documentation: prerequisites, including supported ocis-web versions and installation

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/web-app-dicom-viewer#64]
Update readme documentation with clear steps for:

- [ ] installation for development
- [ ] App installation (on server)
- [ ] description of functionalities (a bit more promotion why this app is awesome)

**Comment by koebel** [comment]
just chatted with @mmattel , having proper documentation is important for next ocis release

**Comment by S-Panta** [comment]
Need to mention csp rule in readme docs.
https://github.com/owncloud/awesome-ocis/blob/0138d4fd966fed78658e813eba6929fd4e4496aa/webApps/apps.json#L374
